apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-pvc
spec:
  capacity:
    storage: 3000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: 10.0.0.1
    path: /exports
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: k8s-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 3000Gi
