apiVersion: v1
kind: PersistentVolume
metadata:
  name: timemachine
spec:
  capacity:
    storage: 3000Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: k8s-nfs.svc.internal.marvinmarvin.de
    path: /exports
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: timemachine
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 3000Gi
