apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8spvc
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
#  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 10.0.0.1
    path: /exports
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: k8spvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
